// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cf-input': string
  'cf-input--checkbox': string
  'cf-input-field': string
  'cf-input-icon': string
  'cf-input-lg': string
  'cf-input-md': string
  'cf-input-pseudo': string
  'cf-input-sm': string
  'cf-input-xs': string
  'cf-input__disabled': string
  'cf-input__error': string
  'cf-input__has-checkbox': string
  'cf-input__has-icon': string
  checked: string
}
export const cssExports: CssExports
export default cssExports
