// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'raw-flux-data-table--cell': string
  'raw-flux-data-table--cell-bg': string
}
export const cssExports: CssExports
export default cssExports
