// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  StatusSpinner: string
  'cf-status-indicator': string
  'cf-status-indicator--child': string
  'cf-status-indicator--shadow': string
  'cf-status-indicator--spinner': string
  'cf-status-indicator__error': string
  'cf-status-indicator__lg': string
  'cf-status-indicator__loading': string
  'cf-status-indicator__md': string
  'cf-status-indicator__sm': string
  'cf-status-indicator__valid': string
  'cf-status-indicator__xs': string
}
export const cssExports: CssExports
export default cssExports
