// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string
  'cf-dapper-scrollbars--track-y': string
  'cf-input': string
  'cf-input-icon': string
  'cf-input-xs': string
  'cf-input__focused': string
  equals: string
  'form-control': string
  key: string
  'table-graph-cell': string
  'table-graph-cell__field-name': string
  'table-graph-cell__fixed-column': string
  'table-graph-cell__fixed-corner': string
  'table-graph-cell__fixed-row': string
  'table-graph-cell__highlight-row': string
  'table-graph-cell__numerical': string
  'table-graph-cell__sort-asc': string
  'table-graph-cell__sort-desc': string
  'time-machine-sidebar': string
  'time-machine-sidebar--filter': string
  'time-machine-sidebar--heading': string
  'time-machine-sidebar--items': string
  'time-machine-sidebar--scroll': string
  'time-machine-sidebar-item': string
  'time-machine-sidebar__light': string
  'time-machine-table': string
  'time-machine-table__light-mode': string
  'time-machine-tables': string
  'time-machines-sidebar--filter': string
  value: string
}
export const cssExports: CssExports
export default cssExports
