#!/bin/bash

set -e 

# Make sure our working dir is the dir of the publish script
cd $(dirname ${BASH_SOURCE[0]})

echo "Fetching git remotes"
git fetch

if ! git status | grep -q 'On branch master'; then
  echo "Error! Must be on master branch to publish"
  exit 1
fi

if ! git status | grep -q "Your branch is up to date with 'origin/master'."; then
  echo "Error! Must be up to date with origin/master to publish"
  exit 1
fi

if ! git status | grep -q 'working tree clean'; then
  echo "Error! Cannot publish with dirty working tree"
  exit 1
fi

echo "Installing dependencies"
yarn -s install --frozen-lockfile

echo "Running tests"
yarn -s run test

echo "Building production build"
yarn run build

RELEASE_TYPE=${1:-patch}

echo "Tagging and publishing $RELEASE_TYPE release"
yarn -s publish --$RELEASE_TYPE --access=public

echo "Pushing git commit and tag"
git push --follow-tags

echo "Publish successful!"
