// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cf-pagination': string;
  'cf-pagination--container': string;
  'cf-pagination--item--container': string;
  'cf-pagination--item--container__active': string;
}
export const cssExports: CssExports;
export default cssExports;
