// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cf-table': string;
  'cf-table--body': string;
  'cf-table--cell': string;
  'cf-table--header': string;
  'cf-table--header-cell': string;
  'cf-table--row': string;
  'cf-table--row__danger': string;
  'cf-table--row__primary': string;
  'cf-table--row__secondary': string;
  'cf-table--row__success': string;
  'cf-table--row__warning': string;
  'cf-table__borders-all': string;
  'cf-table__borders-both': string;
  'cf-table__borders-horizontal': string;
  'cf-table__borders-none': string;
  'cf-table__borders-vertical': string;
  'cf-table__font-sm': string;
  'cf-table__highlight': string;
  'cf-table__striped': string;
}
export const cssExports: CssExports;
export default cssExports;
