// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'giraffe-layer-single-stat': string;
}
export const cssExports: CssExports;
export default cssExports;
