// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'cf-button': string;
  'cf-button--label': string;
  'cf-button-icon': string;
  'cf-button-md': string;
  'cf-button-spinner': string;
  'cf-button-square': string;
  'cf-button-tertiary': string;
}
export const cssExports: CssExports;
export default cssExports;
