// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ButtonSpinner': string;
  'active': string;
  'cf-button': string;
  'cf-button--disabled': string;
  'cf-button--label': string;
  'cf-button--loading': string;
  'cf-button-colorless': string;
  'cf-button-danger': string;
  'cf-button-default': string;
  'cf-button-icon': string;
  'cf-button-lg': string;
  'cf-button-md': string;
  'cf-button-primary': string;
  'cf-button-secondary': string;
  'cf-button-sm': string;
  'cf-button-spinner': string;
  'cf-button-square': string;
  'cf-button-stretch': string;
  'cf-button-success': string;
  'cf-button-tertiary': string;
  'cf-button-warning': string;
  'cf-button-xs': string;
  'cf-dropdown--button': string;
}
export const cssExports: CssExports;
export default cssExports;
