// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cf-dapper-scrollbars': string;
  'cf-dapper-scrollbars--track-x': string;
  'cf-table': string;
  'cf-table--cell': string;
  'cf-table--header-cell': string;
  'visualization--simple-table': string;
  'visualization--simple-table--paging': string;
  'visualization--simple-table--paging-label': string;
  'visualization--simple-table--results': string;
}
export const cssExports: CssExports;
export default cssExports;
